sudo pacman -Sy --noconfirm --needed \
    alacritty \
    brightnessctl \
    btop \
    chromium \
    curl \
    dpkg \
    dunst \
    evince \
    ffmpegthumbnailer \
    firefox \
    gnome-calculator \
    gnome-keyring \
    grim \
    gvfs-mtp \
    gvfs-smb \
    hyprland \
    hypridle \
    hyprlock \
    hyprpaper \
    hyprpicker \
    hyprsunset \
    impala \
    imv \
    iwd \
    kitty \
    kooha \
    less \
    libreoffice-still \
    man-db \
    mpv \
    nautilus \
    noto-fonts \
    noto-fonts-emoji \
    nwg-displays \
    pipewire \
    polkit-gnome \
    qt5-wayland \
    qt6-wayland \
    remmina \
    satty \
    slurp \
    sushi \
    tmux \
    otf-font-awesome \
    papirus-icon-theme \
    unzip \
    uwsm \
    vim \
    vlc \
    waybar \
    wget \
    wireplumber \
    wl-clipboard \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-hyprland

yay -S --noconfirm blueberry walker elephant elephant-desktopapplications brave-bin spotify
